name = "webos"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# R2 bucket for file storage
[[r2_buckets]]
binding = "FILES"
bucket_name = "webos-files"

# KV namespace for user settings
[[kv_namespaces]]
binding = "SETTINGS"
id = "66e352bbad954b22b80d5e91f60d3635"
